name: Publish core

on:
  push:
    branches:
      - "monorepo"
    paths:
      - "packages/core/package.json"
      - "packages/core/**"

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Conditional Publish (core)

    steps:
      - uses: actions/checkout@v4

      - name: Check version change
        id: check_version
        working-directory: packages/core
        run: |
          if git cat-file -e HEAD^:packages/core/package.json; then
            OLD_VERSION=$(git show HEAD^:packages/core/package.json | jq -r '.version')
          else
            OLD_VERSION=""
          fi
          NEW_VERSION=$(jq -r '.version' package.json)

          echo "Old version: $OLD_VERSION"
          echo "New version: $NEW_VERSION"

          if [ "$OLD_VERSION" != "$NEW_VERSION" ]; then
            echo "publish=true" >> $GITHUB_OUTPUT
          else
            echo "publish=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node
        if: steps.check_version.outputs.publish == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20
        env:
          DISABLE_V8_COMPILE_CACHE: 1

      - name: Install Yarn
        if: steps.check_version.outputs.publish == 'true'
        run: npm install -g yarn

      - name: Install dependencies
        if: steps.check_version.outputs.publish == 'true'
        working-directory: packages/core
        run: yarn install --no-immutable

      - name: Build
        if: steps.check_version.outputs.publish == 'true'
        working-directory: packages/core
        run: yarn build

      - name: Publish
        if: steps.check_version.outputs.publish == 'true'
        working-directory: packages/core
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
