name: Publish core

on:
  push:
    branches:
      - "monorepo"
    paths:
      - "packages/core/package.json"
      - "packages/core/**"

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Conditional Publish (core)

    steps:
      - uses: actions/checkout@v4

      - name: Check version change
        id: check_version
        working-directory: packages/core
        run: |
          if git diff HEAD^ HEAD -- package.json | grep '"version":'; then
            echo "Version changed."
            echo "publish=true" >> $GITHUB_OUTPUT
          else
            echo "Version unchanged."
            echo "publish=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node
        if: steps.check_version.outputs.publish == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20
        env:
          DISABLE_V8_COMPILE_CACHE: 1

      - name: Enable Corepack
        if: steps.check_version.outputs.publish == 'true'
        run: corepack enable

      - name: Install dependencies
        if: steps.check_version.outputs.publish == 'true'
        run: yarn install --no-immutable

      - name: Build
        if: steps.check_version.outputs.publish == 'true'
        working-directory: packages/core
        run: yarn build

      - name: Publish
        if: steps.check_version.outputs.publish == 'true'
        working-directory: packages/core
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
